<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CmsUserOrg\Factory\Validator\TerminationDateValidatorFactory' => __DIR__ . '/src/Factory/Validator/TerminationDateValidatorFactory.php',
    'CmsUserOrg\Mapping\ExperienceInterface'                       => __DIR__ . '/src/Mapping/ExperienceInterface.php',
    'CmsUserOrg\Mapping\MetadataInterface'                         => __DIR__ . '/src/Mapping/MetadataInterface.php',
    'CmsUserOrg\Mapping\OrgMetadatableInterface'                   => __DIR__ . '/src/Mapping/OrgMetadatableInterface.php',
    'CmsUserOrg\Mapping\Traits\OrgMetadatableTrait'                => __DIR__ . '/src/Mapping/Traits/OrgMetadatableTrait.php',
    'CmsUserOrg\Mapping\Traits\UserMetadatableTrait'               => __DIR__ . '/src/Mapping/Traits/UserMetadatableTrait.php',
    'CmsUserOrg\Mapping\UserMetadatableInterface'                  => __DIR__ . '/src/Mapping/UserMetadatableInterface.php',
    'CmsUserOrg\Module'                                            => __DIR__ . '/src/Module.php',
    'CmsUserOrg\Mvc\Controller\AdminController'                    => __DIR__ . '/src/Mvc/Controller/AdminController.php',
    'CmsUserOrg\Mvc\Controller\UserController'                     => __DIR__ . '/src/Mvc/Controller/UserController.php',
    'CmsUserOrgTest\Framework\TestCase'                            => __DIR__ . '/tests/Framework/TestCase.php',
    'CmsUserOrgTest\SampleTest'                                    => __DIR__ . '/tests/SampleTest.php',
);
