<?php 
/**
 * CoolMS2 User organization module (http://www.coolms.com/)
 * 
 * @link      http://github.com/coolms/CmsUserOrg for the canonical source repository
 * @copyright Copyright (c) 2006-2015 Altgraphic, ALC (http://www.altgraphic.com)
 * @license   http://www.coolms.com/license/new-bsd New BSD License
 * @author    Dmitry Popov <d.popov@altgraphic.com>
 */

namespace CmsUserOrg;

$this->fieldset = $this->form->get('user')->get('orgMetadata');

$fildset = $this->fieldset->get(0)->get('contactMetadata');
$fildset->remove('websites')
        ->remove('socialNetworks');
?>
<?= $this->render('cms-user-org/metadata/form');
