<?php 
/**
 * CoolMS2 User organization module (http://www.coolms.com/)
 * 
 * @link      http://github.com/coolms/CmsUserOrg for the canonical source repository
 * @copyright Copyright (c) 2006-2015 Altgraphic, ALC (http://www.altgraphic.com)
 * @license   http://www.coolms.com/license/new-bsd New BSD License
 * @author    Dmitry Popov <d.popov@altgraphic.com>
 */

namespace CmsUserOrg;

// Set translation and namespace options here

$this->formCollection()->setTranslatorTextDomain(__NAMESPACE__);
$this->formLabel()->setTranslatorTextDomain(__NAMESPACE__);
$this->formMessages()->setTranslatorTextDomain(__NAMESPACE__);
$this->formRow()->setTranslatorTextDomain(__NAMESPACE__);

// Set form fields classes and placeholders here

$form = $this->form;

$form->setAttributes([
        'class' => 'form-horizontal cms-form cms-user-org-form cms-user-org-form-metadata',
        'role'  => 'form',
    ])->setLabelAttributes([
        'twb'   => ['class' => 'panel-title'],
    ]);

$form->get('submit')->setOptions([
        'twb' => [
            'decorators' => [
                'col' => ['class' => 'col-xs-12 col-sm-8'],
                'formGroup' => ['elements' => 'reset'],
            ],
        ],
    ]);

$form->get('reset')->setOptions([
        'twb' => [
            'decorators' => [
                'col' => ['class' => 'col-xs-12 col-sm-4'],
            ],
        ],
    ]);

$form->prepare();

?>
<?= $this->form()->openTag($form); ?>
  <div class="panel panel-primary">
    <?php if ($form->getLabel()): ?>
    <div class="panel-heading">
      <?= $this->glyphicon('user'); ?>&nbsp;&nbsp;<?= $this->formLabel($form); ?>
    </div>
    <?php endif; ?>
    <div class="panel-body">
      <?= $this->formMessages($form); ?>
      <?= $this->formCollection($this->fieldset ?: $form->get('orgMetadata')); ?>
    </div>
    <div class="panel-footer clearfix">
      <?php if ($form->hasCsrf()): ?>
        <?= $this->formRow($form->getCsrf()); ?>
      <?php endif; ?>
      <?= $this->formRow($form->get('submit')); ?>
    </div>
  </div>
<?= $this->form()->closeTag();
