<?php 
/**
 * CoolMS2 User Organization Module (http://www.coolms.com/)
 *
 * @link      http://github.com/coolms/user-org for the canonical source repository
 * @copyright Copyright (c) 2006-2015 Altgraphic, ALC (http://www.altgraphic.com)
 * @license   http://www.coolms.com/license/new-bsd New BSD License
 * @author    Dmitry Popov <d.popov@altgraphic.com>
 */

namespace CmsUserOrg;

// Set translation and namespace options here
$this->formCollection()->setTranslatorTextDomain(__NAMESPACE__);
$this->formLabel()->setTranslatorTextDomain(__NAMESPACE__);
$this->formMessages()->setTranslatorTextDomain(__NAMESPACE__);
$this->formRow()->setTranslatorTextDomain(__NAMESPACE__);
$this->label()->setTranslatorTextDomain(__NAMESPACE__);

// Set form fields classes and placeholders here
$this->form->setLabelOption('twbs', [
    'element' => [
        'type' => 'label',
        'class' => 'panel-title',
    ],
]);

?>
<?= $this->formPanel($this->form);
